routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'GiatMapController@index');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/acara','AcaraController@index')->name('acara');

/*
 * Giatmus Routes
 */
Route::get('/giatmus-all', 'GiatMapController@index')->name('giatmu_map.index');
Route::resource('giatmus', 'GiatmuController');

/*
 * GiatmuCategories Routes
 */
Route::resource('giatmu_categories', 'GiatmuCategoryController');

app/GiatmuCategory.php
<?php

namespace App;

use App\User;
use App\Giatmu;
use Illuminate\Database\Eloquent\Model;

class GiatmuCategory extends Model
{
    protected $fillable = ['name', 'description', 'creator_id'];

    public function getNameLinkAttribute()
    {
        $title = __('app.show_detail_title', [
            'name' => $this->name, 'type' => __('giatmu_category.giatmu_category'),
        ]);
        $link = '<a href="'.route('giatmu_categories.show', $this).'"';
        $link .= ' title="'.$title.'">';
        $link .= $this->name;
        $link .= '</a>';

        return $link;
    }

    public function creator()
    {
        return $this->belongsTo(User::class);
    }

    public function giatmu()
    {
	return $this->hasMany(Giatmu::class);
    }
}

app/Http/Controllers/GiatmuCategoryController.php
<?php

namespace App\Http\Controllers;

use App\GiatmuCategory;
use Illuminate\Http\Request;

class GiatmuCategoryController extends Controller
{
    /**
     * Display a listing of the giatmuCategory.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $editableGiatmuCategory = null;
        $giatmuCategoryQuery = GiatmuCategory::query();
        $giatmuCategoryQuery->where('name', 'like', '%'.request('q').'%');
        $giatmuCategories = $giatmuCategoryQuery->paginate(25);

        if (in_array(request('action'), ['edit', 'delete']) && request('id') != null) {
            $editableGiatmuCategory = GiatmuCategory::find(request('id'));
        }

        return view('giatmu_categories.index', compact('giatmuCategories', 'editableGiatmuCategory'));
    }

    /**
     * Store a newly created giatmuCategory in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        $this->authorize('create', new GiatmuCategory);

        $newGiatmuCategory = $request->validate([
            'name'        => 'required|max:60',
            'description' => 'nullable|max:255',
        ]);
        $newGiatmuCategory['creator_id'] = auth()->id();

        GiatmuCategory::create($newGiatmuCategory);

        return redirect()->route('giatmu_categories.index');
    }

    /**
     * Update the specified giatmuCategory in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\GiatmuCategory  $giatmuCategory
     * @return \Illuminate\Routing\Redirector
     */
    public function update(Request $request, GiatmuCategory $giatmuCategory)
    {
        $this->authorize('update', $giatmuCategory);

        $giatmuCategoryData = $request->validate([
            'name'        => 'required|max:60',
            'description' => 'nullable|max:255',
        ]);
        $giatmuCategory->update($giatmuCategoryData);

        $routeParam = request()->only('page', 'q');

        return redirect()->route('giatmu_categories.index', $routeParam);
    }

    /**
     * Remove the specified giatmuCategory from storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\GiatmuCategory  $giatmuCategory
     * @return \Illuminate\Routing\Redirector
     */
    public function destroy(Request $request, GiatmuCategory $giatmuCategory)
    {
        $this->authorize('delete', $giatmuCategory);

        $request->validate(['giatmu_category_id' => 'required']);

        if ($request->get('giatmu_category_id') == $giatmuCategory->id && $giatmuCategory->delete()) {
            $routeParam = request()->only('page', 'q');

            return redirect()->route('giatmu_categories.index', $routeParam);
        }

        return back();
    }
}

resources/views/giatmu_categories/forms.blade.php
@if (Request::get('action') == 'create')
@can('create', new App\GiatmuCategory)
    <form method="POST" action="{{ route('giatmu_categories.store') }}" accept-charset="UTF-8">
        {{ csrf_field() }}
        <div class="form-group">
            <label for="name" class="form-label">{{ __('giatmu_category.name') }} <span class="form-required">*</span></label>
            <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required>
            {!! $errors->first('name', '<span class="invalid-feedback" role="alert">:message</span>') !!}
        </div>
        <div class="form-group">
            <label for="description" class="form-label">{{ __('giatmu_category.description') }}</label>
            <textarea id="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" rows="4">{{ old('description') }}</textarea>
            {!! $errors->first('description', '<span class="invalid-feedback" role="alert">:message</span>') !!}
        </div>
        <input type="submit" value="{{ __('giatmu_category.create') }}" class="btn btn-success">
        <a href="{{ route('giatmu_categories.index') }}" class="btn btn-link">{{ __('app.cancel') }}</a>
    </form>
@endcan
@endif
@if (Request::get('action') == 'edit' && $editableGiatmuCategory)
@can('update', $editableGiatmuCategory)
    <form method="POST" action="{{ route('giatmu_categories.update', $editableGiatmuCategory) }}" accept-charset="UTF-8">
        {{ csrf_field() }} {{ method_field('patch') }}
        <div class="form-group">
            <label for="name" class="form-label">{{ __('giatmu_category.name') }} <span class="form-required">*</span></label>
            <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name', $editableGiatmuCategory->name) }}" required>
            {!! $errors->first('name', '<span class="invalid-feedback" role="alert">:message</span>') !!}
        </div>
        <div class="form-group">
            <label for="description" class="form-label">{{ __('giatmu_category.description') }}</label>
            <textarea id="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" rows="4">{{ old('description', $editableGiatmuCategory->description) }}</textarea>
            {!! $errors->first('description', '<span class="invalid-feedback" role="alert">:message</span>') !!}
        </div>
        <input name="page" value="{{ request('page') }}" type="hidden">
        <input name="q" value="{{ request('q') }}" type="hidden">
        <input type="submit" value="{{ __('giatmu_category.update') }}" class="btn btn-success">
        <a href="{{ route('giatmu_categories.index', Request::only('q', 'page')) }}" class="btn btn-link">{{ __('app.cancel') }}</a>
        @can('delete', $editableGiatmuCategory)
            <a href="{{ route('giatmu_categories.index', ['action' => 'delete', 'id' => $editableGiatmuCategory->id] + Request::only('page', 'q')) }}" id="del-giatmu_category-{{ $editableGiatmuCategory->id }}" class="btn btn-danger float-right">{{ __('app.delete') }}</a>
        @endcan
    </form>
@endcan
@endif
@if (Request::get('action') == 'delete' && $editableGiatmuCategory)
@can('delete', $editableGiatmuCategory)
    <div class="card">
        <div class="card-header">{{ __('giatmu_category.delete') }}</div>
        <div class="card-body">
            <label class="form-label text-primary">{{ __('giatmu_category.name') }}</label>
            <p>{{ $editableGiatmuCategory->name }}</p>
            <label class="form-label text-primary">{{ __('giatmu_category.description') }}</label>
            <p>{{ $editableGiatmuCategory->description }}</p>
            {!! $errors->first('giatmu_category_id', '<span class="invalid-feedback" role="alert">:message</span>') !!}
        </div>
        <hr style="margin:0">
        <div class="card-body text-danger">{{ __('giatmu_category.delete_confirm') }}</div>
        <div class="card-footer">
            <form method="POST" action="{{ route('giatmu_categories.destroy', $editableGiatmuCategory) }}" accept-charset="UTF-8" onsubmit="return confirm(&quot;{{ __('app.delete_confirm') }}&quot;)" class="del-form float-right" style="display: inline;">
                {{ csrf_field() }} {{ method_field('delete') }}
                <input name="giatmu_category_id" type="hidden" value="{{ $editableGiatmuCategory->id }}">
                <input name="page" value="{{ request('page') }}" type="hidden">
                <input name="q" value="{{ request('q') }}" type="hidden">
                <button type="submit" class="btn btn-danger">{{ __('app.delete_confirm_button') }}</button>
            </form>
            <a href="{{ route('giatmu_categories.index', Request::only('q', 'page')) }}" class="btn btn-link">{{ __('app.cancel') }}</a>
        </div>
    </div>
@endcan
@endif

resources/views/giatmu_categories/index.blade.php
@extends('layouts.app')

@section('title', __('giatmu_category.list'))

@section('content')
<div class="mb-3">
    <div class="float-right">
        @can('create', new App\GiatmuCategory)
            <a href="{{ route('giatmu_categories.index', ['action' => 'create']) }}" class="btn btn-success">{{ __('giatmu_category.create') }}</a>
        @endcan
    </div>
    <h1 class="page-title">{{ __('giatmu_category.list') }} <small>{{ __('app.total') }} : {{ $giatmuCategories->total() }} {{ __('giatmu_category.giatmu_category') }}</small></h1>
</div>

<div class="row">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">
                <form method="GET" action="" accept-charset="UTF-8" class="form-inline">
                    <div class="form-group">
                        <label for="q" class="form-label">{{ __('giatmu_category.search') }}</label>
                        <input placeholder="{{ __('giatmu_category.search_text') }}" name="q" type="text" id="q" class="form-control mx-sm-2" value="{{ request('q') }}">
                    </div>
                    <input type="submit" value="{{ __('giatmu_category.search') }}" class="btn btn-secondary">
                    <a href="{{ route('giatmu_categories.index') }}" class="btn btn-link">{{ __('app.reset') }}</a>
                </form>
            </div>
            <table class="table table-sm table-responsive-sm table-hover">
                <thead>
                    <tr>
                        <th class="text-center">{{ __('app.table_no') }}</th>
                        <th>{{ __('giatmu_category.name') }}</th>
                        <th>{{ __('giatmu_category.description') }}</th>
                        <th class="text-center">{{ __('app.action') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($giatmuCategories as $key => $giatmuCategory)
                    <tr>
                        <td class="text-center">{{ $giatmuCategories->firstItem() + $key }}</td>
                        <td>{{ $giatmuCategory->name }}</td>
                        <td>{{ $giatmuCategory->description }}</td>
                        <td class="text-center">
                            @can('update', $giatmuCategory)
                                <a href="{{ route('giatmu_categories.index', ['action' => 'edit', 'id' => $giatmuCategory->id] + Request::only('page', 'q')) }}" id="edit-giatmu_category-{{ $giatmuCategory->id }}">{{ __('app.edit') }}</a>
                            @endcan
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="card-body">{{ $giatmuCategories->appends(Request::except('page'))->render() }}</div>
        </div>
    </div>
    <div class="col-md-4">
        @if(Request::has('action'))
        @include('giatmu_categories.forms')
        @endif
    </div>
</div>
@endsection