routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'GiatMapController@index');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/acara','AcaraController@index')->name('acara');

/*
 * Giatmus Routes
 */
Route::get('/giatmus-all', 'GiatMapController@index')->name('giatmu_map.index');
Route::resource('giatmus', 'GiatmuController');

/*
 * GiatmuCategories Routes
 */
Route::resource('giatmu_categories', 'GiatmuCategoryController');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    Selamat Datang, Ayo berkontribusi dengan mendaftarkan kegiatan Lawan Covid di daerahmu. <br>
                    Silakan akses menu <a href="{{ route('giatmus.index') }}"> List Giatmu </a> untuk melihat daftar kegiatan dan tambahkan kegiatanmu disana.<br>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection