routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'GiatMapController@index');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/acara','AcaraController@index')->name('acara');

/*
 * Giatmus Routes
 */
Route::get('/giatmus-all', 'GiatMapController@index')->name('giatmu_map.index');
Route::resource('giatmus', 'GiatmuController');

/*
 * GiatmuCategories Routes
 */
Route::resource('giatmu_categories', 'GiatmuCategoryController');

app/Giatmu.php
<?php

namespace App;

use App\User;
use App\GiatmuCategory;
use Illuminate\Database\Eloquent\Model;

class Giatmu extends Model
{
    protected $fillable = ['name', 'description','giatmu_category_id', 'tanggal','lokasi','url','latitude','longitude','creator_id'];

    public $appends = [
        'coordinate', 'map_popup_content',
    ];

    public function getNameLinkAttribute()
    {
        $title = __('app.show_detail_title', [
            'name' => $this->name, 'type' => __('giatmu.giatmu'),
        ]);
        $link = '<a href="'.route('giatmus.show', $this).'"';
        $link .= ' title="'.$title.'">';
        $link .= $this->name;
        $link .= '</a>';

        return $link;
    }

    public function getUrlLinkAttribute()
    {
        $link = '<a href="'.$this->url.'"';
        $link .= ' title="'.$this->url.'">';
        $link .= $this->url;
        $link .= '</a>';

        return $link;
    }

    public function creator()
    {
        return $this->belongsTo(User::class);
    }

    public function category()
    {
	return $this->belongsTo(GiatmuCategory::class,'giatmu_category_id');
    }

    /**
    * Get outlet coordinate attribute.
    *
    * @return string|null
    */
   public function getCoordinateAttribute()
   {
       if ($this->latitude && $this->longitude) {
           return $this->latitude.', '.$this->longitude;
       }
   }
   // copas dari https://github.com/nafiesl/laravel-leaflet-example
   /**
    * Get outlet map_popup_content attribute.
    *
    * @return string
    */
   public function getMapPopupContentAttribute()
   {
       $mapPopupContent = '';
       $mapPopupContent .= '<div class="my-2"><strong>'.__('giatmu.name').':</strong><br>'.$this->name_link.'</div>';
       $mapPopupContent .= '<div class="my-2"><strong>'.__('giatmu.description').':</strong><br>'.$this->description.'</div>';
       $mapPopupContent .= '<div class="my-2"><strong>'.__('giatmu.category').':</strong><br>'.$this->category->name.'</div>';
       $mapPopupContent .= '<div class="my-2"><strong>'.__('giatmu.url').':</strong><br>'.$this->url_link.'</div>';
       $mapPopupContent .= '<div class="my-2"><strong>'.__('giatmu.coordinate').':</strong><br>'.$this->coordinate.'</div>';

       return $mapPopupContent;
   }
}

app/Http/Controllers/Api/GiatmuController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Giatmu;
use App\Http\Resources\Giatmu as GiatmuResource;

class GiatmuController extends Controller
{
  public function index(Request $request)
  {
      $giatmus = Giatmu::with('category')->get();

      $geoJSONdata = $giatmus->map(function ($giatmu) {
          return [
              'type'       => 'Feature',
              'properties' => new GiatmuResource($giatmu),
              'geometry'   => [
                  'type'        => 'Point',
                  'coordinates' => [
                      $giatmu->longitude,
                      $giatmu->latitude,
                  ],
              ],
          ];
      });

      return response()->json([
          'type'     => 'FeatureCollection',
          'features' => $geoJSONdata,
      ]);
  }
}

app/Http/Controllers/GiatmuController.php
<?php

namespace App\Http\Controllers;

use App\Giatmu;
use App\GiatmuCategory;
use Illuminate\Http\Request;

class GiatmuController extends Controller
{
    /**
     * Display a listing of the giatmu.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $editableGiatmu = null;
        $giatmuQuery = Giatmu::query();
        $giatmuQuery->where('name', 'like', '%'.request('q').'%');
        $giatmus = $giatmuQuery->paginate(25);

        if (in_array(request('action'), ['edit', 'delete']) && request('id') != null) {
            $editableGiatmu = Giatmu::find(request('id'));
        }

        return view('giatmus.index', compact('giatmus', 'editableGiatmu'));
    }

    public function create()
    {
        $this->authorize('create', new Giatmu);
        $data['categories'] = GiatmuCategory::get();

        return view('giatmus.create',$data);
    }

    /**
     * Store a newly created giatmu in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        $this->authorize('create', new Giatmu);
        //dd($request);
        $newGiatmu = $request->validate([
            'name'        => 'required|max:60',
            'description' => 'nullable|max:255',
            'giatmu_category_id' => 'required',
            'tanggal'           => 'required',
            'lokasi'            => 'required',
            'url'               => 'required',
            'latitude'          => 'nullable|required_with:longitude|max:15',
            'longitude'         => 'nullable|required_with:latitude|max:15',
        ]);
        $newGiatmu['creator_id'] = auth()->id();

        Giatmu::create($newGiatmu);

        return redirect()->route('giatmus.index');
    }



    public function show(Giatmu $giatmu)
    {
        return view('giatmus.show', compact('giatmu'));
    }


    public function edit(Giatmu $giatmu)
    {
        $this->authorize('update', $giatmu);
        $data['categories'] = GiatmuCategory::get();

        return view('giatmus.edit', compact('giatmu','data'));
    }

    public function update(Request $request, Giatmu $giatmu)
    {
        $this->authorize('update', $giatmu);

        $giatmuData = $request->validate([
          'name'        => 'required|max:60',
          'description' => 'nullable|max:255',
          'giatmu_category_id' => 'required',
          'tanggal'           => 'required',
          'lokasi'            => 'required',
          'url'               => 'required',
          'latitude'          => 'nullable|required_with:longitude|max:15',
          'longitude'         => 'nullable|required_with:latitude|max:15',
        ]);
        $giatmu->update($giatmuData);

        return redirect()->route('giatmus.show', $giatmu);
    }



    /**
     * Remove the specified giatmu from storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Giatmu  $giatmu
     * @return \Illuminate\Routing\Redirector
     */
    public function destroy(Request $request, Giatmu $giatmu)
    {
        $this->authorize('delete', $giatmu);

        $request->validate(['giatmu_id' => 'required']);

        if ($request->get('giatmu_id') == $giatmu->id && $giatmu->delete()) {
            $routeParam = request()->only('page', 'q');

            return redirect()->route('giatmus.index', $routeParam);
        }

        return back();
    }
}

resources/views/giatmus/create.blade.php
@extends('layouts.app')

@section('title', __('giatmu.create'))

@section('content')
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">{{ __('giatmu.create') }}</div>
            <form method="POST" action="{{ route('giatmus.store') }}" accept-charset="UTF-8">
                {{ csrf_field() }}
                <div class="card-body">
                    <div class="form-group">
                        <label for="name" class="control-label">{{ __('giatmu.name') }}</label>
                        <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required>
                        {!! $errors->first('name', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="description" class="control-label">{{ __('giatmu.description') }}</label>
                        <textarea id="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" rows="4">{{ old('description') }}</textarea>
                        {!! $errors->first('description', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="giatmu_category_id" class="control-label">{{ __('giatmu_category.name') }}</label>
                        <select name="giatmu_category_id" class="form-control{{ $errors->has('giatmu_category_id')? ' is-invalid' : ''}}" name="giatmu_category_id" required>
                          @if(count($categories) > 0) @foreach($categories as $category)
                            <option value="{{$category->id}}">{{$category->name}}</option>
                          @endforeach @endif
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="tanggal" class="control-label">{{ __('giatmu.tanggal') }}</label>
                        <input id="tanggal" type="date" class="form-control{{ $errors->has('tanggal') ? ' is-invalid' : '' }}" name="tanggal" value="{{ old('tanggal') }}" required>
                        {!! $errors->first('tanggal', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="lokasi" class="control-label">{{ __('giatmu.lokasi') }}</label>
                        <textarea id="lokasi" class="form-control{{ $errors->has('lokasi') ? ' is-invalid' : '' }}" name="lokasi" rows="2">{{ old('lokasi') }}</textarea>
                        {!! $errors->first('lokasi', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="url" class="control-label">{{ __('giatmu.url') }}</label>
                        <input id="url" type="text" class="form-control{{ $errors->has('url') ? ' is-invalid' : '' }}" name="url" value="{{ old('url') }}" required>
                        {!! $errors->first('url', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="latitude" class="control-label">{{ __('giatmu.latitude') }}</label>
                                <input id="latitude" type="text" class="form-control{{ $errors->has('latitude') ? ' is-invalid' : '' }}" name="latitude" value="{{ old('latitude', request('latitude')) }}" required>
                                {!! $errors->first('latitude', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="longitude" class="control-label">{{ __('giatmu.longitude') }}</label>
                                <input id="longitude" type="text" class="form-control{{ $errors->has('longitude') ? ' is-invalid' : '' }}" name="longitude" value="{{ old('longitude', request('longitude')) }}" required>
                                {!! $errors->first('longitude', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                            </div>
                        </div>
                    </div>
                    <div id="mapid"></div>
                </div>
                <div class="card-footer">
                    <input type="submit" value="{{ __('giatmu.create') }}" class="btn btn-success">
                    <a href="{{ route('giatmus.index') }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@section('styles')
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
    integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
    crossorigin=""/>

<style>
    #mapid { height: 300px; }
</style>
@endsection

@push('scripts')
<script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
    integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
    crossorigin=""></script>
<script>
    var mapCenter = [{{ request('latitude', config('leaflet.map_center_latitude')) }}, {{ request('longitude', config('leaflet.map_center_longitude')) }}];
    var map = L.map('mapid').setView(mapCenter, {{ config('leaflet.zoom_level') }});

    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);

    var marker = L.marker(mapCenter).addTo(map);
    function updateMarker(lat, lng) {
        marker
        .setLatLng([lat, lng])
        .bindPopup("Your location :  " + marker.getLatLng().toString())
        .openPopup();
        return false;
    };

    map.on('click', function(e) {
        let latitude = e.latlng.lat.toString().substring(0, 15);
        let longitude = e.latlng.lng.toString().substring(0, 15);
        $('#latitude').val(latitude);
        $('#longitude').val(longitude);
        updateMarker(latitude, longitude);
    });

    var updateMarkerByInputs = function() {
        return updateMarker( $('#latitude').val() , $('#longitude').val());
    }
    $('#latitude').on('input', updateMarkerByInputs);
    $('#longitude').on('input', updateMarkerByInputs);
</script>
@endpush

resources/views/giatmus/edit.blade.php
@extends('layouts.app')

@section('title', __('giatmu.edit'))

@section('content')
<div class="row justify-content-center">
    <div class="col-md-6">
        @if (request('action') == 'delete' && $giatmu)
        @can('delete', $giatmu)
            <div class="card">
                <div class="card-header">{{ __('giatmu.delete') }}</div>
                <div class="card-body">
                    <label class="control-label text-primary">{{ __('giatmu.name') }}</label>
                    <p>{{ $giatmu->name }}</p>
                    <label class="control-label text-primary">{{ __('giatmu.lokasi') }}</label>
                    <p>{{ $giatmu->lokasi }}</p>
                    <label class="control-label text-primary">{{ __('giatmu.latitude') }}</label>
                    <p>{{ $giatmu->latitude }}</p>
                    <label class="control-label text-primary">{{ __('giatmu.longitude') }}</label>
                    <p>{{ $giatmu->longitude }}</p>
                    {!! $errors->first('giatmu_id', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                </div>
                <hr style="margin:0">
                <div class="card-body text-danger">{{ __('giatmu.delete_confirm') }}</div>
                <div class="card-footer">
                    <form method="POST" action="{{ route('giatmus.destroy', $giatmu) }}" accept-charset="UTF-8" onsubmit="return confirm(&quot;{{ __('app.delete_confirm') }}&quot;)" class="del-form float-right" style="display: inline;">
                        {{ csrf_field() }} {{ method_field('delete') }}
                        <input name="giatmu_id" type="hidden" value="{{ $giatmu->id }}">
                        <button type="submit" class="btn btn-danger">{{ __('app.delete_confirm_button') }}</button>
                    </form>
                    <a href="{{ route('giatmus.edit', $giatmu) }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                </div>
            </div>
        @endcan
        @else
        <div class="card">
            <div class="card-header">{{ __('giatmu.edit') }}</div>
            <form method="POST" action="{{ route('giatmus.update', $giatmu) }}" accept-charset="UTF-8">
                {{ csrf_field() }} {{ method_field('patch') }}
                <div class="card-body">

                    <div class="form-group">
                        <label for="name" class="control-label">{{ __('giatmu.name') }}</label>
                        <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name', $giatmu->name) }}" required>
                        {!! $errors->first('name', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="description" class="control-label">{{ __('giatmu.description') }}</label>
                        <textarea id="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" rows="4">{{ old('description',$giatmu->description) }}</textarea>
                        {!! $errors->first('description', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="giatmu_category_id" class="control-label">{{ __('giatmu_category.name') }}</label>
                        <select name="giatmu_category_id" class="form-control{{ $errors->has('giatmu_category_id')? ' is-invalid' : ''}}" name="giatmu_category_id" required>
                          @if(count($data['categories']) > 0) @foreach($data['categories'] as $category)
                            <option value="{{$category->id}}" {{ old('giatmu_category_id', $giatmu->giatmu_category_id) == $category->id ? 'selected' : '' }}>{{$category->name}}</option>
                          @endforeach @endif
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="tanggal" class="control-label">{{ __('giatmu.tanggal') }}</label>
                        <input id="tanggal" type="date" class="form-control{{ $errors->has('tanggal') ? ' is-invalid' : '' }}" name="tanggal" value="{{ old('tanggal',$giatmu->tanggal) }}" required>
                        {!! $errors->first('tanggal', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>

                    <div class="form-group">
                        <label for="lokasi" class="control-label">{{ __('giatmu.lokasi') }}</label>
                        <textarea id="lokasi" class="form-control{{ $errors->has('lokasi') ? ' is-invalid' : '' }}" name="lokasi" rows="4">{{ old('lokasi', $giatmu->lokasi) }}</textarea>
                        {!! $errors->first('lokasi', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="url" class="control-label">{{ __('giatmu.url') }}</label>
                        <input id="url" type="text" class="form-control{{ $errors->has('url') ? ' is-invalid' : '' }}" name="url" value="{{ old('url',$giatmu->url) }}" required>
                        {!! $errors->first('url', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="latitude" class="control-label">{{ __('giatmu.latitude') }}</label>
                                <input id="latitude" type="text" class="form-control{{ $errors->has('latitude') ? ' is-invalid' : '' }}" name="latitude" value="{{ old('latitude', $giatmu->latitude) }}" required>
                                {!! $errors->first('latitude', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="longitude" class="control-label">{{ __('giatmu.longitude') }}</label>
                                <input id="longitude" type="text" class="form-control{{ $errors->has('longitude') ? ' is-invalid' : '' }}" name="longitude" value="{{ old('longitude', $giatmu->longitude) }}" required>
                                {!! $errors->first('longitude', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                            </div>
                        </div>
                    </div>
                    <div id="mapid"></div>
                </div>
                <div class="card-footer">
                    <input type="submit" value="{{ __('giatmu.update') }}" class="btn btn-success">
                    <a href="{{ route('giatmus.show', $giatmu) }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                    @can('delete', $giatmu)
                        <a href="{{ route('giatmus.edit', [$giatmu, 'action' => 'delete']) }}" id="del-giatmu-{{ $giatmu->id }}" class="btn btn-danger float-right">{{ __('app.delete') }}</a>
                    @endcan
                </div>
            </form>
        </div>
    </div>
</div>
@endif
@endsection

@section('styles')
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
    integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
    crossorigin=""/>

<style>
    #mapid { height: 300px; }
</style>
@endsection

@push('scripts')
<script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
    integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
    crossorigin=""></script>
<script>
    var mapCenter = [{{ $giatmu->latitude }}, {{ $giatmu->longitude }}];
    var map = L.map('mapid').setView(mapCenter, {{ config('leaflet.detail_zoom_level') }});

    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);

    var marker = L.marker(mapCenter).addTo(map);
    function updateMarker(lat, lng) {
        marker
        .setLatLng([lat, lng])
        .bindPopup("Your location :  " + marker.getLatLng().toString())
        .openPopup();
        return false;
    };

    map.on('click', function(e) {
        let latitude = e.latlng.lat.toString().substring(0, 15);
        let longitude = e.latlng.lng.toString().substring(0, 15);
        $('#latitude').val(latitude);
        $('#longitude').val(longitude);
        updateMarker(latitude, longitude);
    });

    var updateMarkerByInputs = function() {
        return updateMarker( $('#latitude').val() , $('#longitude').val());
    }
    $('#latitude').on('input', updateMarkerByInputs);
    $('#longitude').on('input', updateMarkerByInputs);
</script>
@endpush

resources/views/giatmus/forms.blade.php
@if (Request::get('action') == 'create')
@can('create', new App\Giatmu)
    <form method="POST" action="{{ route('giatmus.store') }}" accept-charset="UTF-8">
        {{ csrf_field() }}
        <div class="form-group">
            <label for="name" class="form-label">{{ __('giatmu.name') }} <span class="form-required">*</span></label>
            <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required>
            {!! $errors->first('name', '<span class="invalid-feedback" role="alert">:message</span>') !!}
        </div>
        <div class="form-group">
            <label for="description" class="form-label">{{ __('giatmu.description') }}</label>
            <textarea id="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" rows="4">{{ old('description') }}</textarea>
            {!! $errors->first('description', '<span class="invalid-feedback" role="alert">:message</span>') !!}
        </div>
        <input type="submit" value="{{ __('giatmu.create') }}" class="btn btn-success">
        <a href="{{ route('giatmus.index') }}" class="btn btn-link">{{ __('app.cancel') }}</a>
    </form>
@endcan
@endif
@if (Request::get('action') == 'edit' && $editableGiatmu)
@can('update', $editableGiatmu)
    <form method="POST" action="{{ route('giatmus.update', $editableGiatmu) }}" accept-charset="UTF-8">
        {{ csrf_field() }} {{ method_field('patch') }}
        <div class="form-group">
            <label for="name" class="form-label">{{ __('giatmu.name') }} <span class="form-required">*</span></label>
            <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name', $editableGiatmu->name) }}" required>
            {!! $errors->first('name', '<span class="invalid-feedback" role="alert">:message</span>') !!}
        </div>
        <div class="form-group">
            <label for="description" class="form-label">{{ __('giatmu.description') }}</label>
            <textarea id="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" rows="4">{{ old('description', $editableGiatmu->description) }}</textarea>
            {!! $errors->first('description', '<span class="invalid-feedback" role="alert">:message</span>') !!}
        </div>
        <input name="page" value="{{ request('page') }}" type="hidden">
        <input name="q" value="{{ request('q') }}" type="hidden">
        <input type="submit" value="{{ __('giatmu.update') }}" class="btn btn-success">
        <a href="{{ route('giatmus.index', Request::only('q', 'page')) }}" class="btn btn-link">{{ __('app.cancel') }}</a>
        @can('delete', $editableGiatmu)
            <a href="{{ route('giatmus.index', ['action' => 'delete', 'id' => $editableGiatmu->id] + Request::only('page', 'q')) }}" id="del-giatmu-{{ $editableGiatmu->id }}" class="btn btn-danger float-right">{{ __('app.delete') }}</a>
        @endcan
    </form>
@endcan
@endif
@if (Request::get('action') == 'delete' && $editableGiatmu)
@can('delete', $editableGiatmu)
    <div class="card">
        <div class="card-header">{{ __('giatmu.delete') }}</div>
        <div class="card-body">
            <label class="form-label text-primary">{{ __('giatmu.name') }}</label>
            <p>{{ $editableGiatmu->name }}</p>
            <label class="form-label text-primary">{{ __('giatmu.description') }}</label>
            <p>{{ $editableGiatmu->description }}</p>
            {!! $errors->first('giatmu_id', '<span class="invalid-feedback" role="alert">:message</span>') !!}
        </div>
        <hr style="margin:0">
        <div class="card-body text-danger">{{ __('giatmu.delete_confirm') }}</div>
        <div class="card-footer">
            <form method="POST" action="{{ route('giatmus.destroy', $editableGiatmu) }}" accept-charset="UTF-8" onsubmit="return confirm(&quot;{{ __('app.delete_confirm') }}&quot;)" class="del-form float-right" style="display: inline;">
                {{ csrf_field() }} {{ method_field('delete') }}
                <input name="giatmu_id" type="hidden" value="{{ $editableGiatmu->id }}">
                <input name="page" value="{{ request('page') }}" type="hidden">
                <input name="q" value="{{ request('q') }}" type="hidden">
                <button type="submit" class="btn btn-danger">{{ __('app.delete_confirm_button') }}</button>
            </form>
            <a href="{{ route('giatmus.index', Request::only('q', 'page')) }}" class="btn btn-link">{{ __('app.cancel') }}</a>
        </div>
    </div>
@endcan
@endif